const alphabet = [
  { character: "A", url: "/sounds/alphabet/a.mp3" },
  { character: "B", url: "/sounds/alphabet/b.mp3" },
  { character: "C", url: "/sounds/alphabet/c.mp3" },
  { character: "D", url: "/sounds/alphabet/d.mp3" },
  { character: "E", url: "/sounds/alphabet/e.mp3" },
  { character: "F", url: "/sounds/alphabet/f.mp3" },
  { character: "G", url: "/sounds/alphabet/g.mp3" },
  { character: "H", url: "/sounds/alphabet/h.mp3" },
  { character: "I", url: "/sounds/alphabet/i.mp3" },
  { character: "J", url: "/sounds/alphabet/j.mp3" },
  { character: "K", url: "/sounds/alphabet/k.mp3" },
  { character: "L", url: "/sounds/alphabet/l.mp3" },
  { character: "M", url: "/sounds/alphabet/m.mp3" },
  { character: "N", url: "/sounds/alphabet/n.mp3" },
  { character: "O", url: "/sounds/alphabet/o.mp3" },
  { character: "P", url: "/sounds/alphabet/p.mp3" },
  { character: "Q", url: "/sounds/alphabet/q.mp3" },
  { character: "R", url: "/sounds/alphabet/r.mp3" },
  { character: "S", url: "/sounds/alphabet/s.mp3" },
  { character: "T", url: "/sounds/alphabet/t.mp3" },
  { character: "U", url: "/sounds/alphabet/u.mp3" },
  { character: "V", url: "/sounds/alphabet/v.mp3" },
  { character: "W", url: "/sounds/alphabet/w.mp3" },
  { character: "X", url: "/sounds/alphabet/x.mp3" },
  { character: "Y", url: "/sounds/alphabet/y.mp3" },
  { character: "Z", url: "/sounds/alphabet/z.mp3" },
];
const numbers = [
  { character: "1", url: "/sounds/numbers/1.wav" },
  { character: "2", url: "/sounds/numbers/2.wav" },
  { character: "3", url: "/sounds/numbers/3.wav" },
  { character: "4", url: "/sounds/numbers/4.wav" },
  { character: "5", url: "/sounds/numbers/5.wav" },
  { character: "6", url: "/sounds/numbers/6.wav" },
  { character: "7", url: "/sounds/numbers/7.wav" },
  { character: "8", url: "/sounds/numbers/8.wav" },
  { character: "9", url: "/sounds/numbers/9.wav" },
  { character: "10", url: "/sounds/numbers/10.wav" },
];

export { numbers, alphabet };
