const alphabet = [
  { letter: 'A', url: '/sounds/alphabet/a.mp3' },
  { letter: 'B', url: '/sounds/alphabet/b.mp3' },
  { letter: 'C', url: '/sounds/alphabet/c.mp3' },
  { letter: 'D', url: '/sounds/alphabet/d.mp3' },
  { letter: 'E', url: '/sounds/alphabet/e.mp3' },
  { letter: 'F', url: '/sounds/alphabet/f.mp3' },
  { letter: 'G', url: '/sounds/alphabet/g.mp3' },
  { letter: 'H', url: '/sounds/alphabet/h.mp3' },
  { letter: 'I', url: '/sounds/alphabet/i.mp3' },
  { letter: 'J', url: '/sounds/alphabet/j.mp3' },
  { letter: 'K', url: '/sounds/alphabet/k.mp3' },
  { letter: 'L', url: '/sounds/alphabet/l.mp3' },
  { letter: 'M', url: '/sounds/alphabet/m.mp3' },
  { letter: 'N', url: '/sounds/alphabet/n.mp3' },
  { letter: 'O', url: '/sounds/alphabet/o.mp3' },
  { letter: 'P', url: '/sounds/alphabet/p.mp3' },
  { letter: 'Q', url: '/sounds/alphabet/q.mp3' },
  { letter: 'R', url: '/sounds/alphabet/r.mp3' },
  { letter: 'S', url: '/sounds/alphabet/s.mp3' },
  { letter: 'T', url: '/sounds/alphabet/t.mp3' },
  { letter: 'U', url: '/sounds/alphabet/u.mp3' },
  { letter: 'V', url: '/sounds/alphabet/v.mp3' },
  { letter: 'W', url: '/sounds/alphabet/w.mp3' },
  { letter: 'X', url: '/sounds/alphabet/x.mp3' },
  { letter: 'Y', url: '/sounds/alphabet/y.mp3' },
  { letter: 'Z', url: '/sounds/alphabet/z.mp3' },
];

export default alphabet;
